Enhance extension installation process and add default dark theme to settings

diff --git a/vscode/rootfs/etc/s6-overlay/s6-rc.d/init-code-server/run b/vscode/rootfs/etc/s6-overlay/s6-rc.d/init-code-server/run
--- a/vscode/rootfs/etc/s6-overlay/s6-rc.d/init-code-server/run
+++ b/vscode/rootfs/etc/s6-overlay/s6-rc.d/init-code-server/run
@@ -24,6 +24,7 @@ readonly -a PREVIOUS_DEFAULT_CONFIG_HASHES=(
     4af003224345302a7f04cf40703554da5a1d8baba512dcb16cf50147f33cf06199f9ef1ddde5a2ecbc5e923ca02d1316ae62588aa9fc439a6cd994576a2b019d
     7588aa36060b1f9a51d83b0e42265021dd99a667fb9d45905e2e3eb5531d8b035dd184d159155e4bdf955e40f5abcc4eaae2905f7a1ad8ee13a95bba9655e34e
     3d23d083ba87534df622d16474fa5340949827afab1206cf01c622411da0b5419c1de0bfd08c55f987004570e751306c84fa843d1a0180ae3e0263dae76a2de0
+    e23284b1cb055f76be07c9f89a7cdefee7ad24b88d3f848600d32f03ea7273ac725d0335bcd4fd84cf135c12642de85faa7515498af7a2eb34ced35dc39563b8
 )
 
 if bashio::config.has_value 'config_path'; then
@@ -60,26 +61,35 @@ while read -r ext; do
     extension="${ext%%#*}"
     version="${ext##*#}"
     vsix="/usr/local/share/code-server/vsix/${extension}-${version}.vsix"
+    installed_path=""
 
     [[ -z "${extension}" ]] && continue
 
     if ! bashio::fs.file_exists "${vsix}"; then
-        bashio::exit.nok "Bundled extension package not found: ${vsix}"
+        bashio::log.warning "Bundled extension package not found: ${vsix}"
+        continue
+    fi
+
+    installed_path=$(find /data/vscode/extensions \
+        -maxdepth 1 \
+        -type d \
+        -iname "${extension}-${version}" \
+        -print \
+        -quit)
+
+    if [[ -n "${installed_path}" ]]; then
+        bashio::log.info "Bundled extension already installed: ${extension} ${version}"
+        continue
     fi
 
     bashio::log.info "Installing bundled extension: ${extension} ${version}"
 
-    find /data/vscode/extensions \
-        -maxdepth 1 \
-        -iname "${extension}-*" \
-        -exec rm -rf '{}' +
-
-    code-server \
+    if ! code-server \
         --user-data-dir /data/vscode \
         --extensions-dir /data/vscode/extensions \
-        --install-extension "${vsix}" \
-        --force \
-        || bashio::exit.nok "Failed installing bundled extension: ${extension}"
+        --install-extension "${vsix}"; then
+        bashio::log.warning "Failed installing bundled extension: ${extension} ${version}"
+    fi
 done < /root/vscode.extensions
 
 # Sets up default user settings on first start.
